apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/linkding/
  - ../../base/audiobookshelf/
  # - cloudflare.yaml
  - ingress.yaml
  - cloudflare-secret.yaml
  - linkding-container-uid-pw-secret.yaml
