apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:T9o1dviEIXI=,iv:IrabomWuzQIdmSd9ZjeQHI/oIV72H2HuCpdcXpa8APA=,tag:u2b6Tj9erccx8c7CPGvNCQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:q6IS00mW8zA1RFWQDOmXGKgpRshIHr5+,iv:+3RzxwwTz5ce2vXmMLfc0o+7ig2X90tg9H+k/oAkJzw=,tag:vSEMEb0qRUgGHjAOS84PbQ==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age1l8m0cssm2t2v4fdwm4d37ptkg6c928egvee4rs03v5k4yry8f94sf9nxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQ3R2UU8wM1JIMTA1M1pl
            NGNXaTdhcHZ6TGNaR0RCZVo2N1ZuV0U3T3c0CkV1SERYazFjekdIOFFuektlMWRI
            NWpURWN2OEgrd1JFUjFvdGlLWEliK0EKLS0tIDlDVGFBZGdldlZ5ZUhzV00xbkJ3
            dnl1STRSY245a1ptYmNPUVI4Q244eHMKESm/CtF5vEUIVDUBQpEpc3Kr/yzqJF7t
            opRGlAKt8EUjF5JVgPdTuGsmiD/ky835Rv6yB+xYf/z0jHpvf9yhoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T07:14:52Z"
    mac: ENC[AES256_GCM,data:k0NspsuQ93fyjrmYz/G6CvwcA2+Cap/HbNPsIpTJP50IKNXV6/CzN3FzoairFAW0EHCiNB4HhobZTfEeb1ZCtZdp2cIVaY3ra007YtLdg7YrlXCL/JT0H6L/ckogosVnfB2eWF6FswcqlQFucvwJHTbqWlevv3RWGhWVxJuYnqo=,iv:H4/nhFH2iibf6Zhm3K8jsa1SQ9fbcFinUHpYXYE5ZlY=,tag:J1Gf0Bii4SwCIskjqXdtag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
